name: Build and Test

on:
  push:
    paths:
      - 'MailTrackerBlocker.xcodeproj/**'
      - 'Source/**'
      - 'Unit Tests/**'
  pull_request_target:
    branches: [main]

jobs:
  upload-release:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: make test
